--- #YAML:1.0
name:                Catalyst-Model-RDBO
version:             0.07
abstract:            **DEPRECATED** base class for Rose::DB::Object model
license:             ~
author:              
    - Peter Karman <perl@peknet.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst::Exception:           0
    Rose::DB::Object:              0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
